FROM node:8.8.1

# update and install dependencies
RUN apt-get update -qq

# install zsh
RUN apt-get install -y zsh
RUN git clone https://github.com/robbyrussell/oh-my-zsh ~/.oh-my-zsh
RUN wget -O /root/.zshrc https://raw.githubusercontent.com/niten2/dotfiles/master/files/zshrc

RUN mkdir -p /app
WORKDIR /app

RUN npm install
